# All in one ZSHRC
echo "[*] Loading Colors..."
# Reset
COL_RESET='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White
echo -e "[${Green}*${COL_RESET}] Sucessfully applied ${Yellow}Regular Colors${COL_RESET}"
# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White
echo -e "[*] Sucessfully applied ${BYellow}Bold Colors${COL_RESET}"
# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White
echo -e "[*] Sucessfully applied ${UYellow}Underline Colors${COL_RESET}"
# Background
bg_Black='\033[40m'       # Black
bg_Red='\033[41m'         # Red
bg_Green='\033[42m'       # Green
bg_Yellow='\033[43m'      # Yellow
bg_Blue='\033[44m'        # Blue
bg_Purple='\033[45m'      # Purple
bg_Cyan='\033[46m'        # Cyan
bg_White='\033[47m'       # White
echo -e "[*] Sucessfully applieg ${bg_White}${BYellow}Background Colors${COL_RESET}"

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White
echo -e "[*] Sucessfully applied ${IYellow}High Intensity Colors${COL_RESET}"
# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White
echo "[*] Sucessfully applied ${BIYellow}Bold High Intensity Colors${COL_RESET}"
# High Intensity backgrounds
bg_IBlack='\033[0;100m'   # Black
bg_IRed='\033[0;101m'     # Red
bg_IGreen='\033[0;102m'   # Green
bg_IYellow='\033[0;103m'  # Yellow
bg_IBlue='\033[0;104m'    # Blue
bg_IPurple='\033[0;105m'  # Purple
bg_ICyan='\033[0;106m'    # Cyan
bg_IWhite='\033[0;107m'   # White
echo "[*] Sucessfully applied ${bg_IWhite}${UBlack}High Intensity Background Colors${COL_RESET}"
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
echo "[*] Loading plugins..."
plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Compilation flags
export ARCHFLAGS="-arch x86_64"
CRIS_NEWSHELL (){
  echo '#!/data/data/com.termux/files/usr/bin/bash' > $1.sh
  chmod +x $1.sh
  $EDITOR $1.sh
}
CRIS_PINGFUNC (){
  if [[ $1 == "" ]]; then
    ping -c 10 -i 0.2 8.8.8.8
  else
    ping -c 10 -i 0.2 $1
  fi
}
# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
echo "[*] Loading alias"
alias zshrc="$EDITOR ~/.zshrc && omz reload"
alias ohmyzsh="cd ~/.oh-my-zsh"
# Changing "ls" to "exa"
alias ls='exa --icons --color=always --group-directories-first'
alias ll='exa -alF --icons --color=always --group-directories-first'
alias la='exa -a --icons --color=always --group-directories-first'
alias l='exa -F --icons --color=always --group-directories-first'
alias l.='exa -a | egrep "^\."'
alias ...="cd ../.."
alias newsh="CRIS_NEWSHELL"
alias rmall="rm -rf"
alias hi="echo 'Hello World'"
alias pong="CRIS_PINGFUNC $1"
alias mk="touch"
alias topen="termux-open"
alias topenurl="termux-open-url"
alias pshell="echo $0 | grep -oE --color=never 'bash|zsh|sh|fish|csh|ksh'"
eval $(starship init zsh)
alias bashrc="eval $EDITOR $PREFIX/etc/bash.bashrc && bash"
clear
echo -e "[${Green}*${COL_RESET}] Loaded .zshrc"

if [[ $(tput cols) -gt 50 ]]; then
echo """   ___     _        _        _         __ ____ 
  / __|_ _(_)___ __| |_ _  _| |_ _  _ /  \__  | 
 | (__| '_| (_-</ _| ' \ || |  _| || | () |/ / 
  \___|_| |_/__/\__|_||_\_,_|\__|\_,_|\__//_/ 
""" | lolcat
else
echo """'     |         |       /~~\~~/
/~~|/~\|(~/~~|/~\|   |~|~|   ||    |/
\__|   |_)\__|   |\_/| |  \_/| \__//
""" | lolcat
fi
neofetch memory
